### ISSUE TITLE
Pluto

### ISSUE THREAD

**Issue by vphill** [somexpert/planets#2]
I think we should really talk about this pluto thing. 

I'm not really sure it *is* a planet.

**Comment by somexpert** [comment]
I learned it was as planet in school, so it _is_ a planet.

**Comment by vphill** [comment]
What about calling it a dwarf planet ? - https://en.wikipedia.org/wiki/Pluto

**Comment by somexpert** [comment]
I'm willing to compromise on that. :thumbsup:

**Comment by vphill** [comment]
Sounds good to me.
